# Generated by Django 5.0.7 on 2024-08-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='col_name',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='title',
            new_name='sub_name',
        ),
    ]
